### ISSUE TITLE
Fix Tilt workflow

### ISSUE THREAD

**Issue by Pothulapati** [deislabs/smi-metrics#47]
Tilt is broken currently, mainly because now there are multiple helm configurations i.e based on the helm chart. 

We need a way to let users create relevant workflow, One option we have is to use a `mesh` env variable and add relevant helm options based on the env value.
https://docs.tilt.dev/api.html#modules.os.environ

@grampelberg

**Comment by grampelberg** [comment]
An easy interim step is to just pick a default and document how to change it for folks. We can come in and put together a more comprehensive solution later.
