### ISSUE TITLE
Move image to a real location

### ISSUE THREAD

**Issue by grampelberg** [deislabs/smi-metrics#6]
The images are using my personal docker account right now, feels like that should be something more general. @slack any good places we could put the images? I'm happy to create an SMI docker hub account.

**Comment by surajssd** [comment]
Yes please let me know about image location, so that the istio adapter images can also be moved there.

**Comment by jshaughn** [comment]
+1, I hit this and had to redirect to my own personal docker account.

**Comment by Pothulapati** [comment]
Closing this, as we use the `deislabs` docker hub now.
