### ISSUE TITLE
More documentation on the SMI APIService

### ISSUE THREAD

**Issue by Pothulapati** [deislabs/smi-metrics#9]
Right now, The spec defines a `CRD` but we only use it for output and this repo is very similar to that of [kubernetes-metrics](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/resource-metrics-api.md). There's a bit of confusion about the approach here especially because of this being different from the implementations of other specs of SMI.

More documentation about the use of `metrics.smi-spec.io` APIService would be helpful for users.

**Comment by jshaughn** [comment]
+1, trying to understand what the SMI TrafficMetrics APIis, how to use it, and what it can do is not straightforward.
